export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      <header className="container mx-auto px-4 py-20 text-center">
        <h1 className="text-6xl font-bold text-gray-900 mb-6">Enterprise AI Agent Platform</h1>
        <p className="text-2xl text-gray-600 mb-8 max-w-3xl mx-auto">Automate customer support, sales, and operations with intelligent AI agents</p>
        <div className="flex gap-4 justify-center">
          <a href="/signup" target="_blank" className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-lg text-lg font-semibold">Join Early Access</a>
          <a href="https://dashboard.stripe.com/test/payment-links/plink_1SedXBB33mCF14xB7iRVPGAe" target="_blank" className="bg-green-600 hover:bg-green-700 text-white px-8 py-4 rounded-lg text-lg font-semibold">Subscribe $100/mo</a>
        </div>
      </header>
      <section className="bg-gray-100 py-12"><div className="container mx-auto px-4 text-center"><p className="text-gray-600 mb-8">Trusted by innovative companies worldwide</p></div></section>
      <section className="container mx-auto px-4 py-20"><h2 className="text-4xl font-bold text-center mb-12">The Challenge</h2><div className="grid md:grid-cols-3 gap-8"><div className="bg-white p-6 rounded-lg shadow"><h3 className="text-xl font-bold mb-4 text-red-600">Manual Support</h3><p>Teams overwhelmed with queries</p></div><div className="bg-white p-6 rounded-lg shadow"><h3 className="text-xl font-bold mb-4 text-red-600">Slow Response</h3><p>Hours of waiting</p></div><div className="bg-white p-6 rounded-lg shadow"><h3 className="text-xl font-bold mb-4 text-red-600">High Costs</h3><p>Expensive resources</p></div></div></section>
      <section className="bg-blue-50 py-20"><div className="container mx-auto px-4"><h2 className="text-4xl font-bold text-center mb-12">The XAXO Solution</h2><div className="grid md:grid-cols-3 gap-8"><div className="bg-white p-6 rounded-lg shadow"><h3 className="text-xl font-bold mb-4 text-blue-600">AI Automation</h3><p>90% queries handled instantly</p></div><div className="bg-white p-6 rounded-lg shadow"><h3 className="text-xl font-bold mb-4 text-blue-600">24/7 Availability</h3><p>Instant responses always</p></div><div className="bg-white p-6 rounded-lg shadow"><h3 className="text-xl font-bold mb-4 text-blue-600">Cost Efficient</h3><p>Reduce costs by 80%</p></div></div></div></section>
      <section className="container mx-auto px-4 py-20"><h2 className="text-4xl font-bold text-center mb-12">Use Cases</h2><div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto"><div className="border-l-4 border-blue-600 pl-6"><h3 className="text-2xl font-bold mb-4">Customer Support</h3><p>Automate FAQs and tracking</p></div><div className="border-l-4 border-green-600 pl-6"><h3 className="text-2xl font-bold mb-4">Sales Automation</h3><p>Qualify leads automatically</p></div></div></section>
      <section className="bg-gray-100 py-20"><div className="container mx-auto px-4"><h2 className="text-4xl font-bold text-center mb-12">How It Works</h2><div className="grid md:grid-cols-3 gap-8"><div className="text-center"><div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">1</div><h3 className="text-xl font-bold mb-4">Connect Systems</h3></div><div className="text-center"><div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">2</div><h3 className="text-xl font-bold mb-4">Train Agent</h3></div><div className="text-center"><div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">3</div><h3 className="text-xl font-bold mb-4">Deploy & Scale</h3></div></div></div></section>
      <section className="container mx-auto px-4 py-20"><h2 className="text-4xl font-bold text-center mb-12">Enterprise Security</h2><div className="grid md:grid-cols-4 gap-6 text-center"><div><div className="text-4xl mb-2">🔒</div><p className="font-bold">SOC 2 Compliant</p></div><div><div className="text-4xl mb-2">🛡️</div><p className="font-bold">GDPR Ready</p></div><div><div className="text-4xl mb-2">🔐</div><p className="font-bold">Encrypted</p></div><div><div className="text-4xl mb-2">⚡</div><p className="font-bold">99.9% Uptime</p></div></div></section>
      <section className="bg-gradient-to-r from-blue-600 to-blue-800 py-20 text-white"><div className="container mx-auto px-4 text-center"><h2 className="text-4xl font-bold mb-6">Simple Pricing</h2><div className="text-6xl font-bold mb-4">$100<span className="text-2xl">/month</span></div><p className="text-xl mb-8">Unlimited conversations</p><a href="https://dashboard.stripe.com/test/payment-links/plink_1SedXBB33mCF14xB7iRVPGAe" target="_blank" className="bg-white text-blue-600 px-8 py-4 rounded-lg text-lg font-semibold inline-block hover:bg-gray-100">Start Subscription</a></div></section>
      <section className="container mx-auto px-4 py-20"><h2 className="text-4xl font-bold text-center mb-12">FAQ</h2><div className="max-w-3xl mx-auto space-y-6"><div className="border-b pb-6"><h3 className="text-xl font-bold mb-2">How long for implementation?</h3><p>Less than 24 hours</p></div><div className="border-b pb-6"><h3 className="text-xl font-bold mb-2">What integrations?</h3><p>All major CRMs and platforms</p></div><div className="border-b pb-6"><h3 className="text-xl font-bold mb-2">Can I cancel?</h3><p>Yes, anytime with no penalties</p></div></div></section>
      <section className="bg-gray-900 text-white py-20"><div className="container mx-auto px-4 text-center"><h2 className="text-4xl font-bold mb-6">Ready to Transform?</h2><div className="flex gap-4 justify-center"><a href="/signup" target="_blank" className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-lg text-lg font-semibold">Join Early Access</a><a href="https://dashboard.stripe.com/test/payment-links/plink_1SedXBB33mCF14xB7iRVPGAe" target="_blank" className="bg-green-600 hover:bg-green-700 text-white px-8 py-4 rounded-lg text-lg font-semibold">Subscribe Now</a></div></div></section>
      <footer className="bg-gray-100 py-12"><div className="container mx-auto px-4 text-center text-gray-600"><p>© 2025 XAXO. All rights reserved.</p></div></footer>
    </div>
  );
}
